% Reference: https://anneurai.net/2016/06/13/prettier-plots-in-matlab/

% general graphics, this will apply to any figure you open
% (groot is the default figure object).
set(groot, ...
'DefaultFigureColor', 'w', ...
'DefaultAxesLineWidth', 0.75, ...
'DefaultAxesXColor', 'k', ...
'DefaultAxesYColor', 'k', ...
'DefaultAxesFontUnits', 'points', ...
'DefaultAxesFontSize', 8, ...
'DefaultAxesFontName', 'Arial', ...
'DefaultLineLineWidth', 2, ...
'DefaultTextFontUnits', 'Points', ...
'DefaultTextFontSize', 8, ...
'DefaultTextFontName', 'Arial', ...
'DefaultAxesBox', 'off');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fig = figure(); 
% centimeters units
X = 21;                  % A4 paper size
Y = 29.7;                  % A4 paper size
xMargin = 1;               % left/right margins from page borders
yMargin = 1;               % bottom/top margins from page borders
xSize = X - 2*xMargin;     % figure size on paper (widht & hieght)
ySize = Y - 2*yMargin;     % figure size on paper (widht & hieght)

% figure size displayed on screen (50% scaled, but same aspect ratio)
set(fig, 'Units','centimeters', 'Position',[0 0 xSize ySize])
movegui(fig, 'center')

% figure size printed on paper
set(fig, 'PaperUnits','centimeters');
set(fig, 'PaperSize',[X Y]);
set(fig, 'PaperPosition',[xMargin yMargin xSize ySize]);
set(fig, 'PaperOrientation','portrait');